### ISSUE TITLE
Support multiple configurations

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/heritageflix#18]
Currently the software the HeritageFlix software is deployed in different versions (paintings, churches) by using separate branches. We want to support a more clear and flexible way of configuring and deploying different version of the HeritageFlix software. May be we should consider a separate configuration repo that holds the configurations for the different versions and facilitates their deployment (under heritage-[name].demo.netwerkdigitaalerfgoed.nl). This should also include a clear instruction (or templates?) to create new versions.

**Comment by ddeboer** [comment]
We now have https://github.com/netwerk-digitaal-erfgoed/heritageflix-configs.

> This should also include a clear instruction (or templates?) to create new versions.

That’s really copy/pasting what we have in that repo, so doesn’t need any docs for now in my opinion.
